import { JsxElement } from "typescript";

export const states = [
  {
    id: 1,
    label: "Abia",
    LGAs: [
      "Aba North",
      "Aba South",
      "Arochukwu",
      "Bende",
      "Ikwuano",
      "Isiala Ngwa North",
      "Isiala Ngwa South",
      "Isukwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma Ngwa",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa West",
      "Umuahia North",
      "Umuahia South",
      "Umu Nneochi",
    ],
  },

  {
    id: 2,
    label: "Adamawa",
    LGAs: [
      "Demsa",
      "Fuforr",
      "Ganye",
      "Girei",
      "Gombi",
      "Guyuk",
      "Hong",
      "Jada",
      "Lamurde",
      "Madagali",
      "Maiha",
      "Mayo-Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numam",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South",
    ],
  },

  {
    id: 3,
    label: "Akwa-Ibom",
    LGAs: [
      "Abak",
      "Estern Obolo",
      "Eket",
      "Esik Eket",
      "Essien Udim",
      "Etim Ekpo",
      "Etinan",
      "Ibesikpo Asutan",
      "Ibeno",
      "Ibiono Ibom",
      "Ika",
      "Ikono",
      "Ikot Abasi",
      "Ikot Epene",
      "Ini",
      "Itu",
      "Mbo",
      "Mkpat Enin",
      "Nsit Atai",
      "Nsit Ibom",
      "Nsit Ubium",
      "Obot Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Oruk Anam",
      "Udung Uko",
      "Ukanafun",
      "Uruan",
      "Urue-Offong/Oruko",
      "Uyo",
    ],
  },

  {
    id: 4,
    label: "Anambra",
    LGAs: [
      "Aguata",
      "Anambra East",
      "Anambra West",
      "Anaocha",
      "Awka North",
      "Awka South",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Idemili North",
      "Idemili South",
      "Ihiala",
      "Njikoka",
      "Nnewi North",
      "Nnewi South",
      "Ogbaru",
      "Onitsha North",
      "Onitsha South",
      "Orumba North",
      "Orumba South",
      "Oyi",
    ],
  },

  {
    id: 5,
    label: "Bauchi",
    LGAs: [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Dambam",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas Gadasu",
      "Jama'are",
      "Katagun",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Belewa",
      "Toro",
      "Warji",
      "Zaki",
    ],
  },

  {
    id: 6,
    label: "Bayelsa",
    LGAs: [
      "Brass",
      "Ekeremor",
      "Kolokuma/Opokum",
      "Nembe",
      "Ogbia",
      "Sagbama",
      "Southern Ijaw",
      "Yenagoa",
    ],
  },

  {
    id: 7,
    label: "Benue",
    LGAs: [
      "Ado",
      "Agatu",
      "Apa",
      "Buruku",
      "Gboko",
      "Guma",
      "Gwer East",
      "Gwer West",
      "Katsina-Ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Obi",
      "Ogbadibo",
      "Ohimini",
      "Oju",
      "Okpokwu",
      "Otukpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya",
    ],
  },

  {
    id: 8,
    label: "Borno",
    LGAs: [
      "Abadam",
      "Askira/Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Gubio",
      "Guzamania",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kala",
      "Konduga",
      "Kukawa",
      "Kwaya",
      "Mafa",
      "Magumeri",
      "Maiduguri",
      "Marte",
      "Mobbar",
      "Monguno",
      "Ngala",
      "Nganzai",
      "Shani",
    ],
  },

  {
    id: 9,
    label: "Cross-River",
    LGAs: [
      "Akpabuyo",
      "Odukpani",
      "Akamkpa",
      "Biase",
      "Abi",
      "Ikom",
      "Yarkur",
      "Odubra",
      "Boki",
      "Ogoja",
      "Yala",
      "Obanliku",
      "Obudu",
      "Calabar South",
      "Etung",
      "Bekwara",
      "Bakassi",
      "Calabar Municipality",
    ],
  },

  {
    id: 10,
    label: "Delta",
    LGAs: [
      "Aniocha North",
      "Aniocha South",
      "Bomadi",
      "Burutu",
      "Ethiope East",
      "Ethiope West",
      "Ika North East",
      "Ika South",
      "Isoko North",
      "Isoko South",
      "Ndokwa East",
      "Ndokwa West",
      "Okpe",
      "Oshimili North",
      "Oshimili South",
      "Patani",
      "Sapele",
      "Udu",
      "Ugheli North",
      "Ugheli South",
      "Ukwuani",
      "Uvwie",
      "Wari North",
      "Warri South",
      "Warri South West",
    ],
  },

  {
    id: 11,
    label: "Ebonyi",
    LGAs: [
      "Abakaliki",
      "Afikpo North",
      "Afikpo South",
      "Ebonyi",
      "Ezza North",
      "Ezza South",
      "ikwo",
      "Ishielu",
      "Ivo-Ebonyi",
      "Izzi",
      "Ohaozara",
      "Ohaukwu",
      "Onicha",
    ],
  },

  {
    id: 12,
    label: "Enugu",
    LGAs: [
      "Aninri",
      "Awgu",
      "Enugu East",
      "Enugu North",
      "Enugu South",
      "Ezeagu",
      "Igbo-Etiti",
      "Igbo Eze North",
      "Igbo Eze South",
      "Isi-Uzo",
      "Nkanu-East",
      "Nkanu-West",
      "nsukka",
      "Oji-River",
      "Udenu",
      "Udi",
      "Uzo-Uwani",
    ],
  },

  {
    id: 13,
    label: "Edo",
    LGAs: [
      "Akoko-Edo",
      "Egor",
      "Esan Central",
      "Esan North-East",
      "Esan South-Eest",
      "Esan West",
      "Etsako Central",
      "Etsako East",
      "Etsako West",
      "Igueben",
      "Ikpoba Okha",
      "Oredo",
      "Orhionmwon",
      "Ovia-North-East",
      "Ovia-South-West",
      "Owan East",
      "Owan West",
      "Uhunmwode",
    ],
  },

  {
    id: 14,
    label: "Ekiti",
    LGAs: [
      "Ado Ekiti",
      "Efon",
      "Ekiti East",
      "Ekiti South West",
      "Ekiti west",
      "Emure",
      "Gbonyin (Aiyekire)",
      "Ido/Osi",
      "Ijero",
      "Ikere",
      "Ikole",
      "Ilejemeje",
      "Irepodun/Ifelodun",
      "Ise/Orun",
      "Moba",
      "Oye",
    ],
  },

  {
    id: 15,
    label: "FCT",
    LGAs: ["Abuja", "Abuja Municipal", "Bwari", "Gwagwalada", "Kuje", "Kwali"],
  },

  {
    id: 16,
    label: "Gombe",
    LGAs: [
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Gombe",
      "Kaltungo",
      "Kwami",
      "Nafada/Bajoga",
      "Shomgom",
      "Yamaltu Deba",
    ],
  },

  {
    id: 17,
    label: "Imo",
    LGAs: [
      "Aboh-Mbaise",
      "Ahiazu-Mbaise",
      "Ehime Mbano",
      "Ezinihitte Mbaise",
      "Ideato North",
      "Ideato South",
      "Ihitte Uboma",
      "Ikeduru",
      "Isiala Mbano",
      "Isu",
      "Mbaitolu",
      "Ngor Okpala",
      "Njaba",
      "Nkwerre",
      "Nwangele",
      "Obowo",
      "Oguta",
      "Ohaji-Egbema",
      "Okigwe",
      "Onuimo",
      "Orlu",
      "Orsu",
      "Oru East",
      "Oru West",
      "Owerri Municipal",
      "Owerri North",
      "Owerri West",
    ],
  },

  {
    id: 18,
    label: "Jigawa",
    LGAs: [
      "Dutse",
      "Kazaure",
      "Auyo",
      "Babura",
      "Birni Kudu",
      "Birniwa",
      "Buji",
      "Gagarawa",
      "Garki",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kaugama",
      "Kiri Kasama",
      "Kiyawa",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Ringim",
      "Roni",
      "Sule Tankarkar",
      "Taura",
      "Yankwashi",
    ],
  },

  {
    id: 19,
    label: "Kaduna",
    LGAs: [
      "Birnin Gwari",
      "Chikun",
      "Giwa",
      "Igaba",
      "Ikara",
      "Jaba",
      "Jema'a",
      "Kachia",
      "Kaduna North",
      "Kaduna South",
      "Kagarko",
      "Kajuru",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sabon Gari",
      "Sanga",
      "Soba",
      "Zangon Kataf",
      "Zaria",
    ],
  },

  {
    id: 20,
    label: "Kano",
    LGAs: [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Dambatta",
      "Dawaki Kudu",
      "Dawaki Tofa",
      "Doguwa",
      "Fagge",
      "Gabasawa",
      "Garko",
      "Garum Mallam",
      "Gaya",
      "Gezawa",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Kano Municipal",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Nasarawa",
      "Rano",
      "Rimin Gado",
      "Rogo",
      "Shanono",
      "Sumaila",
      "Takai",
      "Tarauni",
      "Tofa",
      "Tsanyawa",
    ],
  },

  {
    id: 21,
    label: "Kastina",
    LGAs: [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Dan-Musa",
      "Dandume",
      "Danja",
      "Duara",
      "Dutsi",
      "Dutsin",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Kastina",
      "Kurfi",
      "Kusada",
      "Mai-Adua",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango",
    ],
  },

  {
    id: 22,
    label: "Kebbi",
    LGAs: [
      "Aliero",
      "Arewa Dandi",
      "Argungun",
      "Augie",
      "Bagudo",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Danko-Wasagu",
      "Fakai",
      "Gwandu",
      "Jega",
      "Kalgo",
      "Koko/Besse",
      "Maiyama",
      "Ngaski",
      "Sakaba",
      "Shanga",
      "Suru",
      "Yauri",
      "Zuru",
    ],
  },

  {
    id: 23,
    label: "Kogi",
    LGAs: [
      "Adavi",
      "Ajaokuta",
      "Ankpa",
      "Bassa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igbalamela",
      "Ijumu",
      "Kabba Bunu",
      "Kogi",
      "Lokoja",
      "Mopa-Muro",
      "Ofu",
      "Ogori-Mangongo",
      "Okehi",
      "Okene",
      "Olamaboro",
      "Omala",
      "Yagba East",
      "Yagba West",
    ],
  },

  {
    id: 24,
    label: "Kwara",
    LGAs: [
      "Asa",
      "Baruten",
      "Edu",
      "Ekiti",
      "Ifelodun",
      "Illorin East",
      "Illorin South",
      "Illorin West",
      "Irepodun",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke-Ero",
      "Oyun",
      "Pategi",
    ],
  },

  {
    id: 25,
    label: "Lagos",
    LGAs: [
      "Ageg",
      "Alimosho",
      "Apapa",
      "Amuwo -Odofin",
      "Ajeromi-Ifelodun",
      "Badagry",
      "Epe",
      "Eti-Osa",
      "Ibeju Lekki",
      "Ifako-Ijayr",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos Island",
      "Lagos Mainland",
      "Mushin",
      "Oshodi-Isolo",
      "Ojo",
      "Shomolu",
      "Surulere",
    ],
  },

  {
    id: 26,
    label: "Nasarawa",
    LGAs: [
      "Akwanga",
      "Awe",
      "Doma",
      "Karu",
      "Keana",
      "Keffi",
      "Kokona",
      "Lafia",
      "Nasarawa Egon",
      "Nasarawa",
      "Obi",
      "Toto",
      "Wamba",
    ],
  },

  {
    id: 27,
    label: "Niger",
    LGAs: [
      "Agaie",
      "Agwara",
      "Bida",
      "Borgu",
      "Bosso",
      "Chanchaga",
      "Edati",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Magama",
      "Mariga",
      "Mashegu",
      "Mokwa",
      "Munya",
      "Paikoro",
      "Rafi",
      "Rijau",
      "Shiroro",
      "Suleja",
      "Tafa",
      "Wushishi",
    ],
  },

  {
    id: 28,
    label: "Ogun",
    LGAs: [
      "Abeokuta North",
      "Abeokuta South",
      "Ado-odo/Ota",
      "Ewekoro",
      "Ifo",
      "Ijebu North East",
      "Ijebu North",
      "Ijebu Ode",
      "Ijebu-East",
      "Ikenne",
      "Imeko Afon",
      "Ipokia",
      "Obafemi Owode",
      "Odeda",
      "Odogbolu",
      "Ogun Waterside",
      "Remo North",
      "Sagamu",
      "Yewa North",
      "Yewa South",
    ],
  },

  {
    id: 29,
    label: "Ondo",
    LGAs: [
      "Akoko North East",
      "Akoko North West",
      "Akoko South East",
      "Akoko South West",
      "Akure North",
      "Akure South",
      "Ese Odo",
      "Idanre",
      "Ifedore",
      "Ileje",
      "Ile Oluji/Okeigbo",
      "Irele",
      "Odigbo",
      "Okitipupa",
      "Ondo East",
      "Ondo West",
      "Ose",
      "Owo",
    ],
  },

  {
    id: 30,
    label: "Osun",
    LGAs: [
      "Atakunmosa East",
      "Atakunmosa West",
      "Ayedaade",
      "Ayedire",
      "Boluwaduro",
      "Boripe",
      "Ede North",
      "Ede South",
      "Egbedore",
      "Ejigbo",
      "Ife Central",
      "Ife East",
      "Ife North",
      "Ife South",
      "Ifedayo",
      "Ifelodun",
      "Ila",
      "Ilesa East",
      "Ilesa West",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Odo Otin",
      "Ola Oluwa",
      "Olorunda",
      "Oriade",
      "Orolu",
      "Osogbo",
    ],
  },

  {
    id: 31,
    label: "Oyo",
    LGAs: [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Egbeda",
      "Ibadan North",
      "Ibadan North East",
      "Ibadan North West",
      "Ibadan South East",
      "Ibadan South West",
      "Ibarapa Central",
      "Ibarapa East",
      "Ibarapa North",
      "Ido",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogbomoso North",
      "Ogbomoso South",
      "Ogo Uluwa",
      "Olorunsogo",
      "Oluyole",
      "Ona Ara",
      "Oorelope",
      "Orire",
      "Oyo East",
      "Oyo West",
      "Saki East",
      "Saki West",
      "Surulere",
    ],
  },

  {
    id: 32,
    label: "Plateau",
    LGAs: [
      "Barkin Ladi",
      "Bassa",
      "Bokkos",
      "Jos East",
      "Jos North",
      "Jos South",
      "Kanam",
      "Kanke",
      "Langtang South",
      "Langtang North",
      "Mangu",
      "Mikang",
      "Panshin",
      "Qua'an",
      "Riyom",
      "Shendam",
      "Wase",
    ],
  },

  {
    id: 33,
    label: "Rivers",
    LGAs: [
      "Abua-Odual",
      "Ahoada East",
      "Ahoada West",
      "Akuku Toru",
      "Andoni",
      "Asari-Toru",
      "Bonny",
      "Degema",
      "Eleme",
      "Emohua",
      "Etche",
      "Gokana",
      "Ikwerre",
      "Khana",
      "Obio/Akpor",
      "Ogba/Egbema/Adoni",
      "Ogu/Bolo",
      "Okrika",
      "Omuma",
      "Opobo/Nekoro",
      "Oyiogbo",
      "Port Harcourt",
      "Tai",
    ],
  },

  {
    id: 34,
    label: "Sokoto",
    LGAs: [
      "Binji",
      "Bodinga",
      "Dange Shuni",
      "Gada",
      "Goronyo",
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Kebbe",
      "Kware",
      "Isa",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Sokoto North",
      "Sokoto South",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
    ],
  },

  {
    id: 35,
    label: "Taraba",
    LGAs: [
      "Ardo Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim Lamido",
      "Kurmi",
      "Lau",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wakuri",
      "Yorro",
      "Zing",
    ],
  },

  {
    id: 36,
    label: "Yobe",
    LGAs: [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Potiskum",
      "Tarmuwa",
      "Yunusari",
      "Yusufari",
    ],
  },

  {
    id: 37,
    label: "Zamfara",
    LGAs: [
      "Anka",
      "Bakura",
      "Birnin Magaji-Kiyaw",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Maru",
      "Shinkafi",
      "Talafa Mafara",
      "Tsafe",
      "Zurmi",
      "",
    ],
  },
];
type opt = {
  label: string;
  id: number;
  lgas: string[];
};
export const statess: opt[] = [
  {
    id: 1,
    label: "Abia",
    lgas: [
      "Aba North",
      "Aba South",
      "Arochukwu",
      "Bende",
      "Ikwuano",
      "Isiala Ngwa North",
      "Isiala Ngwa South",
      "Isukwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma Ngwa",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa West",
      "Umuahia North",
      "Umuahia South",
      "Umu Nneochi",
    ],
  },
  {
    id: 2,
    label: "Adamawa",
    lgas: [
      "Demsa",
      "Fuforr",
      "Ganye",
      "Girei",
      "Gombi",
      "Guyuk",
      "Hong",
      "Jada",
      "Lamurde",
      "Madagali",
      "Maiha",
      "Mayo-Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numam",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South",
    ],
  },
];

export type FormControls = {
  emailVerificationCode?:string,
  type?: string;
  name: string;
  label: string | any;
  control: string;
  options?: {}[];
  fieldToCheckAgainst?: string;
  valueOfFieldToCheckAgainst?: any;
  required?: boolean;
  helperText?: string;
  autoComplete?: string;
  handleChange?: any;
  initiaValues?: any;
  checked?: boolean;
  checkedValue?:string,
  url?:string
};
export type FormControlObject = {
  initialValues: any;
  validationSchema: {};
  onSubmit: (...params: any) => void;
  formControls: FormControls[];
};

export const getOptions = (cat: string, value?: string, options?: any[]) => {
  if (value && cat.toLowerCase() === "lga") {
    const state = options?.find((state: any) => state.label === value) as any;
    const lgas =
      state &&
      state.LGAs.map((val: string, i: number) => {
        return { id: i + 1, label: val };
      });

    return lgas;
  }
  return options;
};

export type FormParams = {
  formObject: FormControlObject;
  buttonLabel: string;
  headerTitle: any;
  startIcon?: any;
  endIcon?: any;
  router?:any
};
export const createFormObject = (
  submitHandler: any,
  validationSchema: any,
  initialValues: any,
  formControls: FormControls[]
) => {
  return {
    initialValues,
    validationSchema,
    onSubmit: submitHandler,
    formControls,
  };
};
